# Generated by Django 4.2.2 on 2023-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('st_id', models.IntegerField()),
                ('city', models.TextField(max_length=10)),
            ],
        ),
    ]
